# Generated by Django 3.1.2 on 2021-01-16 19:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, verbose_name='почтовый адрес')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tagline', models.TextField(verbose_name='слоган')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('create_date', models.DateField(auto_now=True, verbose_name='create')),
                ('pub_date', models.DateField(verbose_name='published')),
                ('mod_date', models.DateField(default=datetime.date.today, verbose_name='modified')),
                ('inactive', models.BooleanField(default=False, verbose_name='inactive')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.author', verbose_name='Автор')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog', verbose_name='Блог')),
                ('coauthors', models.ManyToManyField(blank=True, default=None, related_name='entries_as_coauthor_set', to='blog.Author', verbose_name='Соавторы')),
            ],
        ),
        migrations.CreateModel(
            name='EntryStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='blog.entry')),
                ('number_of_comments', models.IntegerField()),
                ('number_of_pingbacks', models.IntegerField()),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_email', models.EmailField(editable=False, max_length=254, verbose_name='email used at registration stage')),
                ('requested', models.DateTimeField(default=datetime.datetime(2021, 1, 16, 21, 30, 38, 645375), editable=False, verbose_name='registration was requested')),
                ('confirmed', models.DateTimeField(default=None, editable=False, null=True, verbose_name='registration was confirmed')),
                ('is_active', models.BooleanField(default=False, editable=False, verbose_name='registration is active')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EntryText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_text', models.TextField(help_text='Содержимое статьи', verbose_name='Блог')),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.entry')),
            ],
        ),
        migrations.CreateModel(
            name='EntryComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField()),
                ('mod_date', models.DateField()),
                ('comment', models.TextField()),
                ('inactive', models.BooleanField(default=False, verbose_name='inactive')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.entry')),
            ],
        ),
    ]
