# Generated by Django 3.1.2 on 2021-01-19 11:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210116_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrytext',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.entry'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='requested',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 19, 13, 47, 18, 172198), editable=False, verbose_name='registration was requested'),
        ),
    ]
