# Generated by Django 3.1.2 on 2021-01-19 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210119_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='create_date',
            field=models.DateField(default=datetime.date(2021, 1, 19), editable=False, verbose_name='create'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='requested',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 19, 16, 31, 46, 755054), editable=False, verbose_name='registration was requested'),
        ),
    ]
