# Generated by Django 3.1.2 on 2021-01-21 16:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_auto_20210121_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='user',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registration',
            name='requested',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 21, 18, 21, 36, 425701), editable=False, verbose_name='registration was requested'),
        ),
    ]
