# Generated by Django 3.1.2 on 2021-01-21 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210121_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='requested',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 21, 18, 25, 36, 889859), editable=False, verbose_name='registration was requested'),
        ),
    ]
