# Generated by Django 3.1.2 on 2021-01-21 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210121_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='create_date',
            field=models.DateField(default=datetime.date.today, editable=False, verbose_name='create'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='requested',
            field=models.DateTimeField(default=datetime.datetime.today, editable=False, verbose_name='registration was requested'),
        ),
    ]
