# Generated by Django 3.1.2 on 2021-02-09 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210121_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrytext',
            name='body_text',
            field=models.TextField(help_text='Содержимое статьи', verbose_name='Text of entry'),
        ),
        migrations.AlterField(
            model_name='entrytext',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.entry', verbose_name='Entry'),
        ),
    ]
