# Generated by Django 3.1.2 on 2021-05-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210209_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tagline',
            field=models.CharField(max_length=128, verbose_name='слоган'),
        ),
    ]
